"use client";

// Kamus bahasa khusus halaman PRD Writer — toggle full ID/EN di sini aja,
// ga ngaruh ke halaman lain.

export const UI_LANGS = [
  { value: "id", label: "Indonesia" },
  { value: "en", label: "English" },
];

export const STRINGS = {
  id: {
    pageTitle: "Penulis PRD",
    pageSub: "Ubah ide singkat jadi dokumen PRD lengkap yang siap dikerjain, pakai model apa pun.",
    uiLangLabel: "Bahasa halaman",
    interviewTitle: "Wawancara PRD",
    interviewSub: "Jawab seadanya — boleh tulis \"lewat\". Makin konkret jawabanmu, makin bagus PRD-nya.",
    interviewDone: "selesai",
    briefTitle: "Ide & Detail",
    addDetails: (n) => `Tambah detail (${n})`,
    hideDetails: "Sembunyiin detail",
    productIdea: "Ide produk",
    productPh: "Contoh: aplikasi catat pemasukan warung buat pemilik warung yang gaptek. Berhasil kalau laporan harian jadi dalam 10 menit.",
    shapeTitle: "Bentuk dokumen",
    profileLabel: "Jenis dokumen",
    depthLabel: "Kedalaman",
    docLangLabel: "Bahasa dokumen",
    maxTokensLabel: "Maks token output",
    maxTokensPh: "0 = bawaan model",
    appendixLabel: "Lampiran glosarium + daftar asumsi",
    sectionsLabel: "Bagian dokumen",
    sectionsCount: (a, b) => `${a} dari ${b} bagian bakal ditulis, urut.`,
    clearAll: "Hapus semua",
    selectAll: "Pilih semua",
    modelsTitle: "Model",
    writerLabel: "Model penulis",
    reviewerLabel: "Model reviewer (opsional)",
    sameAsWriter: (m) => `Sama kayak penulis: ${m}`,
    pickWriterPh: "Pilih model yang nulis PRD ini",
    reviewLabel: "Review — kritik draft, lalu tulis ulang",
    generate: "Bikin PRD",
    writing: "Nulis...",
    reviewing: "Nge-review...",
    stop: "Stop",
    promptBtn: "Prompt",
    needModel: "Pilih model penulis dulu sebelum generate.",
    needIdea: "Tambahin ide atau nama produk biar dokumen ada bahasannya.",
    previewTab: "Hasil",
    markdownTab: "Markdown",
    save: "Simpan",
    update: "Perbarui",
    copy: "Salin",
    taskList: "Daftar tugas",
    sectionsUnit: "bagian",
    outTokens: (n) => `${n} token keluar`,
    emptyTitle: "Belum ada dokumen",
    emptySub: "Tulis idenya, pilih model penulis, terus generate — hasilnya muncul di bawah lengkap sama checklist bagian.",
    writingDoc: "Lagi nulis dokumen...",
    checklistTitle: "Checklist bagian",
    complete: "lengkap",
    missing: (n) => `${n} kurang`,
    critiqueTitle: "Kritik reviewer",
    savedTitle: "Dokumen tersimpan",
    savedCount: (n) => `${n} tersimpan`,
    savedEmpty: "Belum ada yang disimpan — bikin PRD terus tekan Simpan.",
    deleteTitle: "Hapus",
    docMeta: (m, s, c) => `${m} · ${s} bagian · ${c} karakter`,
    taskModal: "Daftar tugas",
    fromPlan: "Dari bagian rencana",
    askModel: (m) => (m ? `Tanya ${m}` : "Tanya model"),
    askModelShort: "Tanya model",
    writingList: "Lagi nulis daftar...",
    askAgain: "Tanya lagi",
    ask: "Tanya",
    needWriterFirst: "Pilih model penulis dulu biar ada yang ditanya.",
    emptyAnswer: "Model jawab kosong, coba tanya lagi.",
    noPlanFound: "Ga ketemu bagian rencana di sini — pindah ke tab tanya model aja.",
    tasksCount: (n) => `${n} ${n === 1 ? "tugas" : "tugas"} urut pengerjaan`,
    followUps: (n) => `${n} item lanjutan`,
    noChecklist: "Belum ada checklist — jalanin request, nanti model yang nulis dari dokumen ini.",
    askingModel: "Lagi nanya model, hasilnya muncul di sini.",
    promptModal: "Prompt yang dikirim ke model",
    promptSub: "Ini instruksi persis yang dikirim pas Generate, biar kelihatan dokumennya diatur gimana.",
    copyPrompt: "Salin prompt",
    rawError: "Lihat error mentah",
    pickWriter: "Pilih model penulis",
    pickReviewer: "Pilih model reviewer",
    askQuestions: "Minta AI nanya",
    askingQ: "Minta pertanyaan...",
    nextRound: (n) => `Lanjut ronde ${n}`,
    finishInterview: (n) => `Selesai — pakai buat PRD (${n} jawaban)`,
    redoInterview: "Ulangi wawancara",
    needPickModel: "Pilih model dulu di panel Model.",
    interviewFail: "Wawancara gagal.",
    assistantTitle: "Asisten Pengisi",
    assistantSub: "Ngobrol bebas — AI bantu isi kotak-kotak di halaman ini. Kalau udah matang, tekan isi otomatis.",
    assistantPh: "Contoh: gw mau bikin aplikasi kasir warung, usernya ibuku yang gaptek...",
    assistantSend: "Kirim",
    assistantThinking: "Mikir...",
    assistantFill: "Isi otomatis ke form",
    assistantFilled: (n) => `${n} kotak terisi`,
    assistantClear: "Hapus sesi",
    assistantNeedModel: "Pilih model penulis dulu (panel Model di atas).",
    assistantEmpty: "Belum ada obrolan — tulis idemu di bawah, AI yang nanya balik.",
    taskFail: "Minta daftar tugas gagal.",
    saveFail: "Gagal simpan PRD",
    genFail: "Generate gagal",
    untitled: "PRD Tanpa Judul",
  },
  en: {
    pageTitle: "PRD Document Writer",
    pageSub: "Turn a short brief into a full, reviewable product requirements document with any model you choose.",
    uiLangLabel: "Page language",
    interviewTitle: "PRD Interview",
    interviewSub: "Answer loosely — you can write \"skip\". The more concrete your answers, the better the PRD.",
    interviewDone: "done",
    briefTitle: "Idea & Details",
    addDetails: (n) => `Add details (${n})`,
    hideDetails: "Hide details",
    productIdea: "Product idea",
    productPh: "Example: an income-tracking app for stall owners who are not tech-savvy. Success = daily report done in 10 minutes.",
    shapeTitle: "Document shape",
    profileLabel: "Profile",
    depthLabel: "Depth",
    docLangLabel: "Document language",
    maxTokensLabel: "Max output tokens",
    maxTokensPh: "0 = model default",
    appendixLabel: "Appendix with glossary and assumption register",
    sectionsLabel: "Sections",
    sectionsCount: (a, b) => `${a} of ${b} sections will be written, in this order.`,
    clearAll: "Clear all",
    selectAll: "Select all",
    modelsTitle: "Models",
    writerLabel: "Writer model",
    reviewerLabel: "Reviewer model (optional)",
    sameAsWriter: (m) => `Same as writer: ${m}`,
    pickWriterPh: "Pick the model that writes this PRD",
    reviewLabel: "Review pass — critique the draft, then rewrite it",
    generate: "Generate PRD",
    writing: "Writing...",
    reviewing: "Reviewing...",
    stop: "Stop",
    promptBtn: "Prompt",
    needModel: "A writer model is required before generating — pick one above.",
    needIdea: "Add an idea or a product name so the document has a subject.",
    previewTab: "Preview",
    markdownTab: "Markdown",
    save: "Save",
    update: "Update",
    copy: "Copy",
    taskList: "Task list",
    sectionsUnit: "sections",
    outTokens: (n) => `${n} out tokens`,
    emptyTitle: "No document yet",
    emptySub: "Describe the idea, pick a writer model, and generate — the result lands below with a section checklist.",
    writingDoc: "Writing the document...",
    checklistTitle: "Section checklist",
    complete: "complete",
    missing: (n) => `${n} missing`,
    critiqueTitle: "Reviewer critique",
    savedTitle: "Saved documents",
    savedCount: (n) => `${n} saved`,
    savedEmpty: "Nothing saved yet — generate a PRD and hit Save to keep it here.",
    deleteTitle: "Delete",
    docMeta: (m, s, c) => `${m} · ${s} sections · ${c} chars`,
    taskModal: "Task list",
    fromPlan: "From plan section",
    askModel: (m) => (m ? `Ask ${m}` : "Ask model"),
    askModelShort: "Ask model",
    writingList: "Writing the list...",
    askAgain: "Ask again",
    ask: "Ask",
    needWriterFirst: "Pick a writer model first so there is something to ask.",
    emptyAnswer: "The model answered with nothing usable, so ask it again.",
    noPlanFound: "Nothing was found in a plan section here, so switch to the model tab and ask it to extract the tasks instead.",
    tasksCount: (n) => `${n} ${n === 1 ? "task" : "tasks"} in dependency order`,
    followUps: (n) => `${n} follow-up items`,
    noChecklist: "No checklist yet — run the request and the model writes one from this document.",
    askingModel: "Asking the model now and the lines show up here as they arrive.",
    promptModal: "Prompt sent to the model",
    promptSub: "This is the exact instruction pair sent on Generate, so you can see how the document is specified.",
    copyPrompt: "Copy prompt",
    rawError: "Show the raw error",
    pickWriter: "Pick writer model",
    pickReviewer: "Pick reviewer model",
    askQuestions: "Ask me questions",
    askingQ: "Asking...",
    nextRound: (n) => `Next: round ${n}`,
    finishInterview: (n) => `Done — use for PRD (${n} answers)`,
    redoInterview: "Redo interview",
    needPickModel: "Pick a model in the Models panel first.",
    interviewFail: "Interview failed.",
    assistantTitle: "Fill Assistant",
    assistantSub: "Free chat — the AI helps fill every box on this page. When it feels ripe, hit auto-fill.",
    assistantPh: "Example: I want a cashier app for my non-technical mom...",
    assistantSend: "Send",
    assistantThinking: "Thinking...",
    assistantFill: "Auto-fill the form",
    assistantFilled: (n) => `${n} boxes filled`,
    assistantClear: "Clear session",
    assistantNeedModel: "Pick the writer model first (Models panel above).",
    assistantEmpty: "No chat yet — type your idea below, the AI asks back.",
    taskFail: "The task list request failed.",
    saveFail: "Failed to save PRD",
    genFail: "Generation failed",
    untitled: "Untitled PRD",
  },
};

// Label + contoh berbahasa manusia (ID) untuk 10 field detail.
export const DETAIL_FIELDS_ID = [
  { key: "product", label: "Nama produk / fitur", placeholder: "cth: KasWarung — catat pemasukan warung" },
  { key: "users", label: "Siapa yang pakai?", placeholder: "cth: pemilik warung 30-50 th, gaptek, HP Android" },
  { key: "problem", label: "Masalahnya apa?", placeholder: "cth: catat manual di buku, sering hilang, ga ada rekap" },
  { key: "stack", label: "Pakai teknologi apa?", placeholder: "cth: Next.js + SQLite, jalan di 1 VPS kecil" },
  { key: "timeline", label: "Target jadi kapan?", placeholder: "cth: 1 bulan, demo ke teman dulu" },
  { key: "team", label: "Siapa yang ngerjain?", placeholder: "cth: gw sendiri + AI, frontend lemah" },
  { key: "constraints", label: "Batasan yang ga bisa diganggu?", placeholder: "cth: tanpa bayar API, hosting gratisan" },
  { key: "nonGoals", label: "Yang JELAS bukan bagian ini?", placeholder: "cth: bukan kasir, bukan multi-cabang, bukan iOS" },
  { key: "metrics", label: "Sukses diukur dari angka apa?", placeholder: "cth: laporan harian jadi maks 10 menit" },
  { key: "notes", label: "Konteks lain", placeholder: "cth: aplikasi sejenis, link contoh, halangan" },
];

export const DETAIL_FIELDS_EN = [
  { key: "product", label: "Product / feature name", placeholder: "e.g. Usage Budget Alerts" },
  { key: "users", label: "Primary users", placeholder: "e.g. solo devs running a self-hosted gateway" },
  { key: "problem", label: "Problem to solve", placeholder: "e.g. nobody notices quota burn until it is gone" },
  { key: "stack", label: "Platform / stack", placeholder: "e.g. Next.js + SQLite, single node" },
  { key: "timeline", label: "Timeline / target date", placeholder: "e.g. ship in 3 weeks, GA next quarter" },
  { key: "team", label: "Team building it", placeholder: "e.g. 1 backend + 1 frontend, 0 designer" },
  { key: "constraints", label: "Hard constraints", placeholder: "e.g. no new infrastructure, offline-first" },
  { key: "nonGoals", label: "Known non-goals", placeholder: "e.g. no billing, no multi-tenant SSO" },
  { key: "metrics", label: "Metrics that matter", placeholder: "e.g. alert precision, quota overruns avoided" },
  { key: "notes", label: "Extra context", placeholder: "prior art, links, politics, anything else" },
];

// Label jenis dokumen + kedalaman versi Indo (EN pakai bawaan prompt.js).
export const TEMPLATE_ID = {
  product: { label: "Produk Baru", hint: "Produk dari nol: pasar, posisi, rencana rilis, spek lengkap." },
  feature: { label: "Fitur Baru", hint: "Fitur di dalam produk yang udah ada user-nya." },
  api: { label: "API / Backend", hint: "Endpoint, kontrak, limit, migrasi, operasional." },
  internal: { label: "Tools Internal", hint: "Tools admin/ops: peran user, jejak audit, panduan jalan." },
  mobile: { label: "Aplikasi HP", hint: "UX HP, offline, rilis store, telemetri." },
  rfc: { label: "RFC / Spek Teknis", hint: "Catatan keputusan desain: opsi ditimbang, pilihan, biaya, risiko." },
  release: { label: "Catatan Rilis", hint: "Rilis yang udah dikirim, ditulis buat manusia: migrasi + isu." },
  competitive: { label: "Bandingin Kompetitor", hint: "Rival dinilai dari fitur, harga, posisi, diakhiri keputusan." },
  incident: { label: "Laporan Bug → Rencana Fix", hint: "Analisa akar masalah sampai fix, verifikasi, pencegahan." },
};

export const DEPTH_ID = {
  standard: { label: "Standar", guidance: "Per bagian: 2-4 poin ringkas atau 1 tabel, maksimal 1 paragraf pendek." },
  deep: { label: "Mendalam", guidance: "Per bagian: 1 tabel atau 4-7 poin + 2 paragraf alasan." },
  exhaustive: { label: "Menyeluruh", guidance: "Per bagian: sub-judul, tabel, 1 contoh nyata berangka, + analisa gagal." },
};

// Pertanyaan wawancara 3 ronde — ID + EN.
export const INTERVIEW_ID = [
  {
    id: "problem",
    title: "Ronde 1 — Masalah & User",
    hint: "Tanpa masalah yang jelas, PRD jadi daftar fitur halu.",
    questions: [
      { key: "problem", label: "Masalah apa yang mau diselesaikan?", example: "Contoh: UMKM susah bikin laporan keuangan, catat manual di buku, sering hilang." },
      { key: "users", label: "Siapa yang paling sakit kena masalah ini?", example: "Contoh: pemilik warung 30-50 tahun, gaptek, HP Android RAM 3GB." },
      { key: "metric", label: "Sukses = angka apa yang berubah?", example: "Contoh: waktu bikin laporan dari 2 jam jadi 10 menit." },
    ],
  },
  {
    id: "limits",
    title: "Ronde 2 — Batas & Scope",
    hint: "Batas yang eksplisit mencegah scope creep.",
    questions: [
      { key: "constraints", label: "Batasan teknis / budget / waktu?", example: "Contoh: 1 dev, 3 minggu, hosting gratisan, tanpa bayar API." },
      { key: "nonGoals", label: "Apa yang JELAS bukan bagian proyek ini?", example: "Contoh: bukan aplikasi kasir, bukan multi-cabang, bukan iOS." },
      { key: "stack", label: "Platform / stack yang dipakai?", example: "Contoh: Next.js + SQLite, jalan di VPS 1GB." },
    ],
  },
  {
    id: "features",
    title: "Ronde 3 — Fitur Kasar",
    hint: "Tulis 3-5 fitur impian — nanti dipaksa jadi P0/P1/P2.",
    questions: [
      { key: "features", label: "3-5 fitur yang dibayangin? (satu baris satu fitur)", example: "Contoh:\n- Catat pemasukan/pengeluaran\n- Laporan bulanan PDF\n- Ingetin stok menipis" },
      { key: "team", label: "Siapa yang ngerjain?", example: "Contoh: gw sendiri + AI, frontend lemah." },
      { key: "timeline", label: "Target jadi kapan?", example: "Contoh: 1 bulan, demo ke teman dulu." },
    ],
  },
];

export const INTERVIEW_EN = [
  {
    id: "problem",
    title: "Round 1 — Problem & Users",
    hint: "Without a clear problem, a PRD becomes a hallucinated feature list.",
    questions: [
      { key: "problem", label: "What problem should this solve?", example: "Example: small shops struggle with bookkeeping, manual notes get lost." },
      { key: "users", label: "Who hurts the most from this problem?", example: "Example: stall owners age 30-50, non-technical, Android phones." },
      { key: "metric", label: "Success = which number changes?", example: "Example: reporting time from 2 hours down to 10 minutes." },
    ],
  },
  {
    id: "limits",
    title: "Round 2 — Limits & Scope",
    hint: "Explicit limits prevent scope creep.",
    questions: [
      { key: "constraints", label: "Technical / budget / time constraints?", example: "Example: 1 dev, 3 weeks, free hosting, no paid APIs." },
      { key: "nonGoals", label: "What is clearly NOT part of this project?", example: "Example: not a cashier app, not multi-branch, not iOS." },
      { key: "stack", label: "Platform / stack?", example: "Example: Next.js + SQLite on a small VPS." },
    ],
  },
  {
    id: "features",
    title: "Round 3 — Rough features",
    hint: "Write 3-5 dream features — they get forced into P0/P1/P2 later.",
    questions: [
      { key: "features", label: "3-5 imagined features? (one per line)", example: "Example:\n- Track income/expenses\n- Monthly PDF report\n- Low-stock reminder" },
      { key: "team", label: "Who is building it?", example: "Example: just me + AI, weak at frontend." },
      { key: "timeline", label: "Target ship date?", example: "Example: 1 month, demo to friends first." },
    ],
  },
];
